require_relative 'generate_cmc_records'

###########################
###   ENTER DATA HERE   ###
###########################

# For environment prefix refer to section 3 (API access) here: https://tools.hmcts.net/confluence/display/ROC/Environment+Links
env_prefix = 'localhost:4400'
path_to_integration_tests = '../../../hmcts/cmc-integration-tests'

claimant_session_id = 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJzanM2Y3RwNThhbmtzdTNpNnNzczRjc2dvZCIsInN1YiI6IjI3IiwiaWF0IjoxNTM2MDUwNDEzLCJleHAiOjE1MzYwNzkyMTMsImRhdGEiOiJjaXRpemVuLGNsYWltYW50LGNpdGl6ZW4tbG9hMSxjbGFpbWFudC1sb2ExIiwidHlwZSI6IkFDQ0VTUyIsImlkIjoiMjciLCJmb3JlbmFtZSI6IkNsYWltIiwic3VybmFtZSI6IkFudCIsImRlZmF1bHQtc2VydmljZSI6ImNtYyIsImxvYSI6MSwiZGVmYXVsdC11cmwiOiJodHRwczovL3d3dy1jaXRpemVuLm1vbmV5Y2xhaW0ucmVmb3JtLmhtY3RzLm5ldDozMDAwL2NtYyIsImdyb3VwIjoiY2l0aXplbnMifQ.sOWOT_F61mOnixfw4hifiX1yncaNx_oYLJVFHhh0yeE'
defendant_session_id = 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJpNGRyc2lycXYzNjVlamFobDFmaG02Z2IydCIsInN1YiI6IjMwIiwiaWF0IjoxNTM2MDUwNDQxLCJleHAiOjE1MzYwNzkyNDEsImRhdGEiOiJjaXRpemVuLGNtYy1wcml2YXRlLWJldGEsbGV0dGVyLWhvbGRlcixsZXR0ZXItaG9sZGVyLGxldHRlci1ob2xkZXIsbGV0dGVyLWhvbGRlcixsZXR0ZXItaG9sZGVyLGxldHRlci1ob2xkZXIsbGV0dGVyLWhvbGRlcixsZXR0ZXItaG9sZGVyLGxldHRlci1ob2xkZXIsbGV0dGVyLWhvbGRlcixsZXR0ZXItaG9sZGVyLGRlZmVuZGFudCxjbGFpbWFudCxsZXR0ZXItMjksbGV0dGVyLTMxLGxldHRlci0zMixsZXR0ZXItMzMsbGV0dGVyLTM0LGxldHRlci0zNSxsZXR0ZXItMzYsbGV0dGVyLTM3LGxldHRlci0zOCxsZXR0ZXItNDAsbGV0dGVyLTM5LGxldHRlci1ob2xkZXIsbGV0dGVyLTQxLGxldHRlci1ob2xkZXIsbGV0dGVyLTQyLGxldHRlci1ob2xkZXIsbGV0dGVyLTQ0LGNpdGl6ZW4tbG9hMSxjbWMtcHJpdmF0ZS1iZXRhLWxvYTEsbGV0dGVyLWhvbGRlci1sb2ExLGxldHRlci1ob2xkZXItbG9hMSxsZXR0ZXItaG9sZGVyLWxvYTEsbGV0dGVyLWhvbGRlci1sb2ExLGxldHRlci1ob2xkZXItbG9hMSxsZXR0ZXItaG9sZGVyLWxvYTEsbGV0dGVyLWhvbGRlci1sb2ExLGxldHRlci1ob2xkZXItbG9hMSxsZXR0ZXItaG9sZGVyLWxvYTEsbGV0dGVyLWhvbGRlci1sb2ExLGxldHRlci1ob2xkZXItbG9hMSxkZWZlbmRhbnQtbG9hMSxjbGFpbWFudC1sb2ExLGxldHRlci0yOS1sb2ExLGxldHRlci0zMS1sb2ExLGxldHRlci0zMi1sb2ExLGxldHRlci0zMy1sb2ExLGxldHRlci0zNC1sb2ExLGxldHRlci0zNS1sb2ExLGxldHRlci0zNi1sb2ExLGxldHRlci0zNy1sb2ExLGxldHRlci0zOC1sb2ExLGxldHRlci00MC1sb2ExLGxldHRlci0zOS1sb2ExLGxldHRlci1ob2xkZXItbG9hMSxsZXR0ZXItNDEtbG9hMSxsZXR0ZXItaG9sZGVyLWxvYTEsbGV0dGVyLTQyLWxvYTEsbGV0dGVyLWhvbGRlci1sb2ExLGxldHRlci00NC1sb2ExIiwidHlwZSI6IkFDQ0VTUyIsImlkIjoiMzAiLCJmb3JlbmFtZSI6IkRlZmVuZCIsInN1cm5hbWUiOiJBbnQiLCJkZWZhdWx0LXNlcnZpY2UiOiJDTUMiLCJsb2EiOjEsImRlZmF1bHQtdXJsIjoiaHR0cHM6Ly93d3ctY2l0aXplbi5tb25leWNsYWltLnJlZm9ybS5obWN0cy5uZXQ6MzAwMC9jbWMiLCJncm91cCI6ImNtYy1wcml2YXRlLWJldGEifQ.r3OgNaBKa3wPqfpERvYrE8mRYqJfhRvzGLuNc4eyd24'

defendant_response = :reject_paid_what_i_believe_i_owe_full
create_result_file = false

##################################
#   EXECUTION RUNS FROM HERE   ###
##################################

args = {
    env_prefix: env_prefix,
    claimant_session_id: claimant_session_id,
    defendant_session_id: defendant_session_id,
    defendant_response: defendant_response,
    path_to_integration_tests: path_to_integration_tests,
    create_result_file: create_result_file
}

GenerateCmcRecords.generate(args)
